### PR TITLE
Added api support for minimum storage space

### PR DESCRIPTION
**Pull request by adampaulberg**
Support for /api/Storage and /api/Storage?minGB=20

### CODE REVIEW

**Comment by jakebrown58** [comment]
can you bump the version if you're adding an API to the installer service.

**Comment by adampaulberg** [comment]
Will do

**Comment by adampaulberg** [comment]
image

**Comment by jakebrown58** [comment]
cool - though wondering if we should add more context to the message:

{
  success: true,
  details: [{
     key: "drivespaceok-driveC",
     descr: "Will there be enough disk space to install?",
     value: "286",
     success: true
  },
  {
     key: "drivespaceok-driveD",
     descr: "Will there be enough disk space to install?",
     value: "1575",
     success: true
  }
  ]
}

**Comment by jakebrown58** [comment]
maybe i'm getting too generic here......

**Comment by adampaulberg** [comment]
I think more context would matter if there was more than 1 thing we are testing, but we're mostly just checking how much space there is and if it's enough.

**Comment by jakebrown58** [comment]
well, we're just checking disk space *right now*.  but this is an API we'll need to live with forever once we publish it.

if this API is just going to be about disk space, then the boolean option is better.

**Comment by jakebrown58** [comment]
also - talked to some prod people and they said the check for 3 gigs, so we should make that the default.  apparently 10 is way too high.   (on a first-time install, 10 would be necessary, but on a first-time install, if you don't have 10 gigs of free space, you've got bigger problems than I think we can solve).

**Comment by adampaulberg** [comment]
drives

**Comment by jakebrown58** [comment]
nice.

**Comment by jakebrown58** [comment]
looks good.

**Pull request merged**
